apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: customPrefixer
suffix: "-staging"
fieldSpecs:
  - kind: Deployment
    group: apps
    path: spec/template/spec/containers/envFrom/secretRef/name
  - kind: Deployment
    group: apps
    path: spec/template/spec/containers/envFrom/configMapRef/name
