apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- config.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: octopus
