apiVersion: v1
kind: Service
metadata:
  name: octopus-service
  namespace: demo
spec:
  selector:
    app: octopus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
