apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/default

nameSuffix: -production

namespace: production-octopus

patchesStrategicMerge:
  - config.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/environment: production
      app.kubernetes.io/instance: api-production
      app.kubernetes.io/name: api-production

transformers:
  - transformer.yaml

replicas:
  - name: octopus-deployment
    count: 3

patchesJson6902:
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: octopus-ingress
      version: v1
  - path: hpa.yaml
    target:
      group: autoscaling
      kind: HorizontalPodAutoscaler
      name: octopus-hpa
      version: v2
