apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

nameSuffix: -production

namespace: production-octopus

patchesStrategicMerge:
  - config.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/environment: production
      app.kubernetes.io/instance: api-production
      app.kubernetes.io/name: api-production

transformers:
  - transformer.yaml

replicas:
  - name: octopus-deployment
    count: 3
