apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octopus
  template:
    metadata:
      labels:
        app: octopus
    spec:
      volumes:
        - name: config-volume
      containers:
        - name: octopus
          image: bpcloudrepository/octopus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: octopus-configmap
            - secretRef:
                name: octopus-secret
