apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/canary

nameSuffix: -canary

namespace: production-octopus

patchesStrategicMerge:
  - config.yaml

transformers:
  - transformer.yaml

replicas:
  - count: 2
    name: octopus-deployment
